### PR TITLE
Axios cache interceptor v1 roadmap

### LINKED ISSUE #317: bug: Request doesn't execute after a abortion.
### Describe the bug

I've experienced that when i try to cancel a request and resubmit it right after, nothing seems to happen.

### To Reproduce

In [this CodePen](https://codepen.io/SamCapri/pen/jOzePLx), if i click the 'Request' button as first, everything seems to be fine, but after a reload, if i click first the 'With Quick Abort', all further requests will not be initiated.

### Expected behavior

After the page load, when 'With Quick Abort' button is clicked, the first request will be aborted, while the second one will be sent and completed.

### Additional context

- Axios: v0.27.2
- Axios Cache Interceptor: v0.10.7
- What storage is being used: MemoryStorage
- Node Version: v16.14.0
- Browser (if applicable): Chrome 104.0.5112.81

P.S.: This plugin is very powerful and easy to use, I hope you can help me or tell me if I'm doing something wrong! 😊

### LINKED ISSUE #367: bug: axios V1.0.0 support
### Describe the bug

A few types are broken when using with axios v1.0.0 due to the being no overlap between axios and axios cache instance.

### To Reproduce

Bump axios to v1.0.0 and use a axios instance as a cache interceptor type.
### Expected behavior

Be able to compile the ts without any error.

### Additional context

- Axios: `1.0.0`
- Axios Cache Interceptor: `latest`
- Error thrown: 
```

Error: src/functions/NitrApi.ts(25,21): error TS2352: Conversion of type 'AxiosInstance' to type 'AxiosCacheInstance' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
123
  Type 'AxiosInstance' is missing the following properties from type 'AxiosCacheInstance': storage, generateKey, waiting, headerInterpreter, and 3 more.
124
Error: src/functions/NitrApi.ts(35,33): error TS2345: Argument of type 'AxiosCacheInstance' is not assignable to parameter of type 'AxiosInstance'.
125
  Types of property 'defaults' are incompatible.
126
    Type 'AxiosDefaults<any> & { cache: CacheProperties<unknown, unknown>; }' is not assignable to type 'Omit<AxiosDefaults<any>, "headers"> & { headers: HeadersDefaults & { [key: string]: AxiosHeaderValue; }; }'.
127
      Type 'AxiosDefaults<any> & { cache: CacheProperties<unknown, unknown>; }' is not assignable to type '{ headers: HeadersDefaults & { [key: string]: AxiosHeaderValue; }; }'.
128
        Types of property 'headers' are incompatible.
129
          Type 'HeadersDefaults' is not assignable to type 'HeadersDefaults & { [key: string]: AxiosHeaderValue; }'.
130
            Type 'HeadersDefaults' is not assignable to type '{ [key: string]: AxiosHeaderValue; }'.
131
              Index signature for type 'string' is missing in type 'HeadersDefaults'.
```

### PR DESCRIPTION
**Pull request by arthurfiorette**
Closes #367.

The current task list for **v1.0.0** seems to be the following:

`(W): Waiting`

- [x] Test types that didn't throw any error.
- [x] Make sure were extending correctly `AxiosInstance`, as it changed dramastically.
- [x] Understand how headers have changed. axios/axios#5002
- [x] Fix old broken tests
- [x] Fix tests js-dom environment with ESM. axios/axios#5000
- [x] Should be added new tests to check for new axios features?
- [x] Migrate docs generator to [vuepress](https://vuepress.vuejs.org) _(or any other beauty template)_.
- [x] Test if axios v1 really fixed #317.
- [x] Make sure node v12+ is still working (#397)

### CODE REVIEW

**Comment by arthurfiorette** [comment]
I'm waiting for a more mature version of axios v1 before continuing this work.

**Comment by arthurfiorette** [comment]
While v1.2+ does not get released, I'll be slowly working on non-axios related features, like the new documentation.

**Comment by arthurfiorette** [comment]
Axios just released 1.2.1, I'm going to get back to this PR.

**Comment by arthurfiorette** [comment]
For new axios features, its safe to say that is currently working fine and I'll add tests for them as soon as any issue comes :)

**Comment by serpaulius** [comment]
Hey, I was looking to install axios-cache-interceptor@1 as written in https://axios-cache-interceptor.js.org/guide/getting-started#quick-start and I now see that such release/tag does not exist, and found this MR which is already merged 🤔
Is there still anything left to be done for the v1 release or it's just a mistake in the docs? 😅
If that is still WIP, will I be safe to use axios@1.2.1 with the axios-cache-interceptor@0.10.7?
thanks!

**Comment by arthurfiorette** [comment]
Hey, actually no. I was testing the new documentation and released it to get more spelling feedback. For now axios-cache-interceptor only works with axios@0.

I'll release the 1.0.0-beta this or next week. This month has been too short in time for me, sorry for the inconvenience.

**Comment by serpaulius** [comment]
No problem, thanks for amazing work and info!

**Comment by KGALLET** [comment]
Thank's for your work Arthur !

**Pull request merged**
