### PR TITLE
Avoid `RangeError: Maximum call stack size exceeded` on streams and other objects

### LINKED ISSUE #608: Avoid `RangeError: Maximum call stack size exceeded` on streams and other objects
Currently, the ID is generated even when you use `cache: false`. The ID should only be created when cache is not false.

https://github.com/arthurfiorette/axios-cache-interceptor/blob/4f88736afc380813c469d888ca70966202bcd14f/src/interceptors/request.ts#L19

This line should be below the `config.cache === false`.

### PR DESCRIPTION
**Pull request by joseiedo**
closes #608

### CODE REVIEW

**Comment by arthurfiorette** [comment]
can you build up a test case?

**Comment by joseiedo** [comment]
sure!

**Comment by joseiedo** [comment]
tried to use this test case
```typescript
  it('expect keyGenerator is not called when using cache: false', async () => {
    const axios = mockAxios();

    const spy = jest.spyOn(axios, 'generateKey');

    await axios.get('http://test.com', { cache: false });

    expect(spy).not.toHaveBeenCalled();
  });
```
but generateKey is still being called 🤔 

the strange thing is that if I use console.log

```typescript
export function defaultRequestInterceptor(axios: AxiosCacheInstance) {
  const onFulfilled: RequestInterceptor['onFulfilled'] = async (config) => {
    if (config.cache === false) {
      if (__ACI_DEV__) {
        axios.debug?.({
          msg: 'Ignoring cache because config.cache === false',
          data: config
        });
      }

      console.log('not going to generatekey');
      return config;
    }

    console.log('gonna generatekey');
    const id = (config.id = axios.generateKey(config));
```

the 'gonna generatekey' console.log doesn't trigger

**Comment by joseiedo** [comment]
@arthurfiorette 
In my last commit 42ad257cf04146ef1fde93379673a8f46ea765c8 I changed when the ID is gonna be generated in `response.ts` too, then needed to change the test that was expecting to have an ID

let me know if I misunderstood the behavior you wanted 

have a great week ✌

**Comment by joseiedo** [comment]
@arthurfiorette 
I changed the `request.ts` too to only generate ID when the cache is not false, then I needed to update one test
Let me know if I misunderstood the behavior you wanted

Have a good week!

**Comment by arthurfiorette** [comment]
I was thinking about this issue today... Key generation should work even if cache is false, to fulfill with our interface requirements and to not break user code which uses request/response.id to unique identify requerts.

I came up with only generating the key if cache is not false because when submitting streams/big objects/circular objects inside params, the key generator would overflow its stack. 

https://github.com/arthurfiorette/axios-cache-interceptor/blob/998e96c9d17e36cf43b4aa13d2d06ca3375d4a65/src/util/key-generator.ts#L61

However I could not reproduce it today, I remember it was throwing when posting FormData with a readable stream in one field... Before merging this PR, I'd like to reproduce it again, if you could try to do it, else I'll do it as soon as I can.

**Comment by joseiedo** [comment]
Since I never worked with streams, maybe I didn't tested right, but I came up with this and everything worked fine:
```ts
 const axios = mockAxios();
    const filePath = './README.md';

    const formData = {
      file: fs.createReadStream(filePath)
    };

    const result = await axios.post('url', {
      data: {
        formData
      }
    });
```

buut when I test with circular objects the error still happens... 
```
    RangeError: Maximum call stack size exceeded
        at toString (<anonymous>)

      at node_modules/axios/lib/utils.js:11:26
      at isPlainObject (node_modules/axios/lib/utils.js:130:7)
      at assignValue (node_modules/axios/lib/utils.js:315:9)
      at forEach (node_modules/axios/lib/utils.js:265:10)             
```

**Comment by arthurfiorette** [comment]
Hey @joseiedo, I've merged with main and made some changes here (somehow history was overwritten XD).

After some talk with my stream chat, we decided that was better to handle recursive properties inside the object-code package and just adapt to that changes here. We've relased v1.3 with the needed fixed and I've updated its version here. I also created another test for it and things should be fine for now...

Thanks for your effort!

**Pull request merged**
