### PR TITLE
fix: remove the response rejection from the response interceptor

### LINKED ISSUE #572: bug: when a site have `dont cache` flag the request rejected
### Describe the bug

I tried to use the interceptor on https://www.iposcoop.com/ipo/cytomed-therapeutics-pte-ltd/ but the site have a `dont cache` flag, instead of just don't use the cache, the lib rejects the request https://github.com/arthurfiorette/axios-cache-interceptor/blob/378574c05915aed929c40fda376649ed99b27c06/src/interceptors/response.ts#L157

### Expected behavior

The request should work properly but just ignore the cache

### PR DESCRIPTION
**Pull request by tupe12334**
Closes #572.

This pull request remove the response rejection from the response interceptor

### CODE REVIEW

**Comment by arthurfiorette** [comment]
Hey @tupe12334, thanks for your PR! Can you add a test and fix the linting problems?

**Comment by tupe12334** [comment]
@arthurfiorette  I fixed the lint problem but the test anyway don't work for me locally and crash here as well.

**Comment by arthurfiorette** [comment]
The above commit was just a merge from main :)

**Comment by arthurfiorette** [comment]
Hey @tupe12334, sorry for just looking into your PR now. What you are trying to achieve here? What is when a site have aa `dont cache` flag? You meant the result of header interpreter? 

The above code you removed was just removing the invalid cache from the storage and resolving other promises that were waiting for this result... The test broke because one promise was waiting to be resolved but you removed the code to resolve it :/

I cannot approve this PR with a plausible reproduction step or more precise debug information to detect if this is even a real bug after all. _(As problems not always are bugs)_

**Comment by arthurfiorette** [comment]
See https://github.com/arthurfiorette/axios-cache-interceptor/issues/572#issuecomment-1640746958

**Pull request closed without merging**
