### PR TITLE
Enhanced the Security Policies

### PR DESCRIPTION
**Pull request by tvermaashutosh**
@arthurfiorette 
I have enhanced and improved the security policies for this package. I have added a general structure and rules people follow for their security policies. I have included your email through which any contributor would report their issues.

### CODE REVIEW

**Comment by tvermaashutosh** [comment]
@arthurfiorette 
Kindly review this PR and merge it. I'm open to any changes you would like to suggest.

**Comment by arthurfiorette** [comment]
Hey @tvermaashutosh, I'm migrating all README related files to my user-wide .github repository, would you mind creating a PR there? (https://github.com/arthurfiorette/.github/blob/main/SECURITY.md). Could you delete this file in this PR?

**Comment by tvermaashutosh** [comment]
> Hey @tvermaashutosh, I'm migrating all README related files to my user-wide .github repository, would you mind creating a PR there? (https://github.com/arthurfiorette/.github/blob/main/SECURITY.md). Could you delete this file in this PR?

@arthurfiorette 
Could you please merge this PR here and then migrate your code there?
I want to contribute in a 200+ stars repo only because I'm competing in HackSquad.

**Comment by arthurfiorette** [comment]
> Could you delete this file in this PR?

This is the requested change. If you are doing this just because you are on HackSquad and not to make this package better, I can close this PR.

**Pull request closed without merging**
