### PR TITLE
Adding an IndexedDB Storage

### PR DESCRIPTION
**Pull request by lucajung**
This pull request introduces an IndexedDB storage implementation for Axios caching. IndexedDB provides a client-side storage solution that can be used to store and retrieve data for efficient caching of Axios requests.

Key Changes:

Added a new module for IndexedDB-based storage.

- Created functions for finding, setting, and removing data from IndexedDB storage.
- Initialized an IndexedDB database and object store for Axios caching.
- Integrated the IndexedDB storage into the Axios caching system.

Code Highlights:

- **getIndexedDbStorage(db: IDBPDatabase<unknown>, storeName: string): BuildStorage**: This function creates an IndexedDB storage object for Axios caching. It includes methods for finding, setting, and removing data based on the provided IndexedDB database and store name.
- **buildIndexedDbStorage(): Promise<AxiosStorage>**: This function initializes the IndexedDB storage by creating the necessary object store and returns an AxiosStorage object, which can be used for caching Axios requests.

Note:

- Since the indexed is only available in browsers, no tests can be designed for this storage without mocking.
- Due to the nature of the IndexedDB interface, a web API was not possible because of asynchrony.

### CODE REVIEW

**Comment by arthurfiorette** [comment]
> Due to the nature of the IndexedDB interface, a web API was not possible because of asynchrony.

You can use `new Promise((resolve, reject) => ...)` to convert callbacks to promises.

**Comment by arthurfiorette** [comment]
> Since the indexed is only available in browsers, no tests can be designed for this storage without mocking.

I cannot merge this without tests, we are already mocking a DOM object to be used, I think it can be used here too.

https://github.com/arthurfiorette/axios-cache-interceptor/blob/main/test/dom.ts

**Comment by arthurfiorette** [comment]
Actually, some of my comments above were misleading... I look into idb and raw indexedDb usage and we should stick with `idb`. It seems waaay more easy to handle and integrate with. Just change it to a peerDependency. I'm not sure if our build step would include idb source into the bundle or just a import to it. A closer look to it should be done after the initial implementation.

**Comment by lucajung** [comment]
I'll have a deeper look into testing idb in the next days/ weeks. Maybe it is possible with the `fake-indexeddb` package.

**Comment by arthurfiorette** [comment]
> Maybe it is possible with the fake-indexeddb package.

Just use this property within the tests.

```ts
// test/dom.ts
dom.window.indexedDB
```

**Comment by lucajung** [comment]
Yes that is good.
I just had the idea if it wouldn't be better to combine the IndexedDB storage with the buildWebStorage interface.
Extending the WebStorage API to a "BrowserStorage Interface". IndexedDB is just like localstorage and sessionstorage by default only available in browsers and not in Node.js.

**Comment by arthurfiorette** [comment]
> I just had the idea if it wouldn't be better to combine the IndexedDB storage with the buildWebStorage interface.

I don't think so, they share different APIs, local/session storage is sync and idb is async. The more split storage methods are the better it will be, as tree shaking can remove more code from being sent to the browser.

**Comment by lucajung** [comment]
@arthurfiorette The `jsdom indexedDB` Property seems to be `undefined`. Can you take a look at it?
> Just use this property within the tests.
> 
> ```ts
> // test/dom.ts
> dom.window.indexedDB
> ```

**Comment by arthurfiorette** [comment]
@lucajung maybe something in their docs would help?
https://github.com/jsdom/jsdom

**Comment by arthurfiorette** [comment]
@lucajung is this ready for review?

**Comment by arthurfiorette** [comment]
Currently, I'll just mention https://github.com/arthurfiorette/axios-cache-interceptor/issues/669#issuecomment-1820679994 at documentation when searching for IndexedDb support.

**Pull request closed without merging**
