### PR TITLE
Migrate docs generator to vitepress

### PR DESCRIPTION
**Pull request by cainthebest**
A possible candidate for documentation. 
Task is referenced in #368 
PR is limited to `./vitepress-docs`

### CODE REVIEW

**Comment by cainthebest** [comment]
@arthurfiorette what do you think of this basic setup, ofc there's a lot more to migrate but is this the direction that you're looking to head in?

image

**Comment by cainthebest** [comment]
Light mode variant

image

**Comment by arthurfiorette** [comment]
Awesome 😎👍

In the oficial PR, there's a docs-new branch, running yarn dev you'll be able to see how it was going when I was doing it :)

**Comment by cainthebest** [comment]
@arthurfiorette i took what you have done with the home page on vuepress and migrated it to this

image
image

**Comment by arthurfiorette** [comment]
Hey! I started moving the new docs content into your branch and noticed that they do not support for code blocks yet... vuejs/vitepress#728

Should we try to glue it in a custom component for now or change all the scripts temporarily?

**Comment by cainthebest** [comment]
I think for now we could just possibly keep as is till its supported, looking at the [PR](https://github.com/vuejs/vitepress/pull/1560) that fixes that issue it seems to be close to completion

**Comment by cainthebest** [comment]
@arthurfiorette have you got discord? I sent a friend request to the one on your profile just as i have a suggestion

**Comment by arthurfiorette** [comment]
Yeah, Arthur Fiorette#0001. I've just sent you a friend request.

**Comment by arthurfiorette** [comment]
I do think that I ended all docs needings. Algolia and carbon ads will have to wait for a first publish and other things can be fixed through other small PRs. Thanks for your help!

**Comment by arthurfiorette** [comment]
The CI is not broken because of this PR.

**Pull request merged**
